# Generated by Django 2.1.2 on 2018-11-19 05:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keywords',
            name='user',
            field=models.ManyToManyField(related_name='selected_keywords', through='filter.KeywordOwner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='locations',
            name='user',
            field=models.ManyToManyField(related_name='selected_areas', through='filter.UserAreas', to=settings.AUTH_USER_MODEL),
        ),
    ]
