# Generated by Django 2.1.2 on 2018-11-26 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0002_auto_20181119_0858'),
    ]

    operations = [
        migrations.AddField(
            model_name='locations',
            name='twittername',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
