# Generated by Django 2.1.2 on 2018-11-30 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0003_locations_twittername'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit', models.IntegerField(blank=True, null=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='areasettings', to='filter.Locations')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='areas', to='filter.UserMarketSettings')),
            ],
        ),
        migrations.CreateModel(
            name='KeywordHit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hit', models.IntegerField(blank=True, null=True)),
                ('keyword', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='keywordsettings', to='filter.Keywords')),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='keywords', to='filter.UserMarketSettings')),
            ],
        ),
        migrations.AddField(
            model_name='keywords',
            name='settings',
            field=models.ManyToManyField(related_name='hit_keywords', through='filter.KeywordHit', to='filter.UserMarketSettings'),
        ),
        migrations.AddField(
            model_name='locations',
            name='settings',
            field=models.ManyToManyField(related_name='hit_areas', through='filter.AreaHit', to='filter.UserMarketSettings'),
        ),
        migrations.AlterUniqueTogether(
            name='keywordhit',
            unique_together={('keyword', 'setting')},
        ),
        migrations.AlterUniqueTogether(
            name='areahit',
            unique_together={('area', 'setting')},
        ),
    ]
