# Generated by Django 2.1.2 on 2018-12-02 21:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0004_auto_20181130_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermarketsettings',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL),
        ),
    ]
