# Generated by Django 2.1.2 on 2018-12-02 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0005_auto_20181203_0008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areahit',
            name='hit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
