# Generated by Django 2.1.2 on 2018-12-07 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('filter', '0006_auto_20181203_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areahit',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hit', to='filter.Locations'),
        ),
        migrations.AlterField(
            model_name='keywordhit',
            name='hit',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
