# Generated by Django 2.1.2 on 2018-11-26 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0002_tweet_screen_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tweet_date',
            field=models.DateField(null=True),
        ),
    ]
