# Generated by Django 2.1.2 on 2018-11-26 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0003_tweet_tweet_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='published_date',
        ),
        migrations.AddField(
            model_name='tweet',
            name='tweet_url',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
