# Generated by Django 2.1.2 on 2018-11-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0004_auto_20181126_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='area',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='tweet',
            name='keyword',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
