# Generated by Django 2.1.2 on 2018-12-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0009_auto_20181208_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reported',
            name='reply_id',
        ),
    ]
