# Generated by Django 2.1.2 on 2018-12-09 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0010_remove_reported_reply_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reported',
            name='report_reason',
            field=models.CharField(default='asdasd', max_length=250),
        ),
    ]
