# Generated by Django 2.1.2 on 2018-12-09 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweets', '0011_auto_20181209_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reported',
            name='report_reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
